# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_user_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
        ),
    ]
