# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='logreg.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(auto_now=True),
        ),
    ]
